language: node_js
node_js:
    - "node"

script:
    - npm test
    - npm update
    - node_modules/.bin/jshint src

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $Token 
    keep_history: true
    on:
    branch: master